export interface LatestGames {
    id: number,
    category: number,
    created_at: Date,
    date: Date,
    game: number,
    human: string,
    m: number,
    platform: number,
    region: number,
    updated_at: Date,
    y: Date,
    checksum: string,
    status: number
}

export interface Game {
    id: number,
    alternative_names: number[],
    category: number,
    cover: number,
    aggregated_rating:string
    created_at: Date,
    external_games: number[],
    first_release_date: number,
    game_modes: number[],
    genres: number[],
    involved_companies: number[],
    keywords: number[],
    name: string,
    platforms: number[],
    player_perspectives: number[],
    release_dates: number[],
    screenshots: number[],
    similar_games: number[],
    slug: string,
    summary: string,
    storyline: string
    tags: number[],
    themes: number[],
    updated_at: Date,
    url: string,
    total_rating:number,
    videos: number[],
    websites: number[],
    checksum: string,
    language_supports: number[],
}
